# Generated by Django 4.0.5 on 2022-06-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_alter_automation_options_remove_automation_plant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('meas_type', models.IntegerField(default=1)),
                ('background_color', models.CharField(default='aqua', max_length=10)),
                ('text_color', models.CharField(default='black', max_length=10)),
                ('unit', models.CharField(default='m³/h', max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='automation.plant')),
            ],
            options={
                'ordering': ['row', 'col'],
            },
        ),
    ]
