# Generated by Django 4.0.5 on 2022-06-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='fill_m3',
            field=models.FloatField(default=0.0),
        ),
    ]
