# Generated by Django 4.0.5 on 2022-06-12 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_tank_fill_m3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sp', models.FloatField(default=50.0)),
                ('mv', models.FloatField(default=0.0)),
                ('p_faktor', models.FloatField(default=0.0)),
                ('i_faktor', models.FloatField(default=0.0)),
                ('d_faktor', models.FloatField(default=0.0)),
                ('on', models.BooleanField(default=False)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pids', to='automation.pump')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pids', to='automation.measurement')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pids', to='automation.plant')),
            ],
        ),
    ]
