# Generated by Django 4.0.5 on 2022-06-12 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0010_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pid',
            name='actuator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pids', to='automation.pump'),
        ),
        migrations.AlterField(
            model_name='pid',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pids', to='automation.measurement'),
        ),
    ]
