# Generated by Django 4.0.5 on 2022-06-15 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0014_alter_recipe_state_alter_recipe_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aos', to='automation.plant')),
            ],
        ),
        migrations.CreateModel(
            name='AutoObject2',
            fields=[
                ('automation2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automation2')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('dim', models.IntegerField(default=60)),
            ],
            bases=('automation.automation2',),
        ),
        migrations.CreateModel(
            name='AutoObject3',
            fields=[
                ('automation2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automation2')),
                ('volume', models.FloatField(default=10.0)),
                ('dim', models.IntegerField(default=60)),
            ],
            bases=('automation.automation2',),
        ),
    ]
