# Generated by Django 4.0.5 on 2022-06-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0015_automation2_autoobject2_autoobject3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoobject3',
            name='automation2_ptr',
        ),
        migrations.DeleteModel(
            name='AutoObject2',
        ),
        migrations.DeleteModel(
            name='AutoObject3',
        ),
    ]
