# Generated by Django 4.0.5 on 2022-06-19 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_remove_autoobject3_automation2_ptr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automation2',
        ),
    ]
