# Generated by Django 4.0.5 on 2022-06-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0017_delete_automation2'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='temperature',
            field=models.FloatField(default=21.0),
        ),
    ]
