# Generated by Django 4.0.5 on 2022-06-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0018_automation_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('automation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automation')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='automation.plant')),
            ],
            bases=('automation.automation',),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('automation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.automation')),
                ('pressure', models.FloatField(default=4.0)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='automation.plant')),
            ],
            bases=('automation.automation',),
        ),
    ]
