# Generated by Django 4.0.5 on 2022-06-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_target_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='material',
            field=models.JSONField(default='[0,0,0]'),
        ),
    ]
