# Generated by Django 4.0.5 on 2022-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0023_reactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactor',
            name='mixing_on',
            field=models.BooleanField(default=False),
        ),
    ]
