# Generated by Django 4.0.5 on 2022-06-22 10:43

import automation.serializers2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0024_reactor_mixing_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='connected',
            field=models.JSONField(default=automation.serializers2.connected_default),
        ),
        migrations.AlterField(
            model_name='automation',
            name='connections',
            field=models.JSONField(default=automation.serializers2.connections_default),
        ),
    ]
